include: package:very_good_analysis/analysis_options.10.1.0.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    discarded_futures: ignore

linter:
  rules:
    public_member_api_docs: false
