name: prf_design
description: PRF Design System - Shared widgets, theme system, and essential utilities.
version: "0.4.0"
repository: https://github.com/PARKROAD-FELLOWSHIP/stunning-fiesta
homepage: https://parkroadfellowship.org
issue_tracker: https://github.com/PARKROAD-FELLOWSHIP/stunning-fiesta/issues

environment:
  sdk: ">=3.10.3 <4.0.0"
  flutter: ">=3.38.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_ui: ^0.8.0+1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.1.0
  google_fonts: ^8.0.2
  http: ^1.6.0
  intl: ^0.20.2
  pdfx: ^2.9.2
  timezone: ^0.11.0

dev_dependencies:
  fake_async: ^1.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  assets:
    - assets/authentication/
    - assets/google_fonts/lato/
    - assets/google_fonts/manrope/
