blank_issues_enabled: false
contact_links:
  - name: Setup and Hosting Assistance
    url: https://parkroadfellowship.org
    about: Contact engineering@parkroadfellowship.org for setup and hosting help.