name: Feature request
description: Propose an enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: input
    id: problem
    attributes:
      label: Problem statement
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true